# Model-vs-control pseudobulk differential expression and fGSEA
# Supports Figure 5.
#
# Input lineage objects are generated by 07_create_lineage_objects.R.
#
# Comparisons:
#   FAT-MASH vs chow
#   HOT-MASH vs chow
#
# Lineages:
#   Hepatocytes
#   Endothelial cells
#   Macrophages
#   HSCs
#
# Internal condition nomenclature retained from the original analysis:
#   CCl4_model = FAT-MASH
#   DEN_model  = HOT-MASH
#   RT_chow    = chow control
#
# Pseudobulk counts are generated by summing raw RNA counts per mouse and
# analyzed with DESeq2.
#
# In the original analysis, fGSEA .rnk files were prepared manually from the
# DESeq2 Wald statistic (`stat`). Here the same ranked vectors are generated
# directly from the DESeq2 results.

library(Seurat)
library(Matrix)
library(DESeq2)
library(fgsea)
library(msigdbr)
library(dplyr)
library(tibble)
library(readr)


# =============================================================================
# Part 1: helper functions
# =============================================================================

# -----------------------------------------------------------------------------
# Pseudobulk raw RNA counts by mouse
# -----------------------------------------------------------------------------

create_pseudobulk <- function(
    object_file,
    counts_output,
    metadata_output
) {
  
  obj <- readRDS(
    object_file
  )
  
  DefaultAssay(obj) <- "RNA"
  
  # Raw counts matrix: genes x cells
  cts <- GetAssayData(
    obj,
    assay = "RNA",
    layer = "counts"
  )
  
  sample_ids <- obj$sample_id
  
  stopifnot(
    length(sample_ids) == ncol(cts)
  )
  
  # Sum counts across all cells from the same mouse
  pb_counts <- sapply(
    unique(sample_ids),
    function(sid) {
      Matrix::rowSums(
        cts[
          ,
          sample_ids == sid,
          drop = FALSE
        ]
      )
    }
  )
  
  pb_counts <- as.matrix(
    pb_counts
  )
  
  # Sample-level metadata
  pb_meta <- obj@meta.data %>%
    as.data.frame() %>%
    group_by(sample_id) %>%
    summarise(
      condition = dplyr::first(condition),
      role = dplyr::first(role),
      n_cells = n(),
      .groups = "drop"
    )
  
  # Match metadata order to count-matrix columns
  pb_meta <- pb_meta[
    match(
      colnames(pb_counts),
      pb_meta$sample_id
    ),
  ]
  
  pb_meta <- as.data.frame(
    pb_meta
  )
  
  rownames(pb_meta) <- pb_meta$sample_id
  
  stopifnot(
    identical(
      colnames(pb_counts),
      rownames(pb_meta)
    )
  )
  
  # Basic pseudobulk QC
  print(
    colSums(pb_counts)
  )
  
  print(
    colSums(pb_counts > 0)
  )
  
  print(
    pb_meta$n_cells
  )
  
  saveRDS(
    pb_counts,
    counts_output
  )
  
  write.csv(
    pb_meta,
    metadata_output,
    row.names = TRUE
  )
  
  rm(obj, cts)
  gc()
  
  list(
    counts = pb_counts,
    metadata = pb_meta
  )
}


# -----------------------------------------------------------------------------
# DESeq2 model-vs-chow analysis
# -----------------------------------------------------------------------------

run_deseq2 <- function(
    pb_counts,
    pb_meta,
    model_condition,
    output_file
) {
  
  pb_meta <- pb_meta[
    colnames(pb_counts),
    ,
    drop = FALSE
  ]
  
  stopifnot(
    identical(
      rownames(pb_meta),
      colnames(pb_counts)
    )
  )
  
  # Chow is the reference level
  pb_meta$condition <- factor(
    pb_meta$condition,
    levels = c(
      "RT_chow",
      model_condition
    )
  )
  
  # Original prefilter:
  # retain genes with at least 10 counts in at least 2 samples
  keep <- rowSums(
    pb_counts >= 10
  ) >= 2
  
  pb_counts_filt <- pb_counts[
    keep,
  ]
  
  dds <- DESeqDataSetFromMatrix(
    countData = round(
      pb_counts_filt
    ),
    colData = pb_meta,
    design = ~ condition
  )
  
  dds <- DESeq(
    dds
  )
  
  res <- results(
    dds,
    contrast = c(
      "condition",
      model_condition,
      "RT_chow"
    ),
    alpha = 0.05
  )
  
  write.table(
    res,
    output_file,
    sep = "\t"
  )
  
  print(
    summary(res)
  )
  
  res
}


# -----------------------------------------------------------------------------
# Convert DESeq2 Wald statistics to the ranked vector used for fGSEA
# -----------------------------------------------------------------------------

make_rank_vector <- function(
    res
) {
  
  rank_df <- data.frame(
    GENE = rownames(res),
    RANK = res$stat,
    stringsAsFactors = FALSE
  ) %>%
    mutate(
      GENE = toupper(
        trimws(GENE)
      )
    ) %>%
    filter(
      !is.na(GENE),
      is.finite(RANK)
    ) %>%
    group_by(GENE) %>%
    slice_max(
      order_by = abs(RANK),
      n = 1,
      with_ties = FALSE
    ) %>%
    ungroup()
  
  stats <- rank_df$RANK
  
  names(stats) <- rank_df$GENE
  
  stats <- stats[
    order(
      stats,
      decreasing = TRUE
    )
  ]
  
  stats
}


# -----------------------------------------------------------------------------
# fGSEA using Hallmark and Reactome gene sets
# -----------------------------------------------------------------------------

run_fgsea <- function(
    res,
    hallmark_list,
    reactome_list,
    output_file
) {
  
  stats <- make_rank_vector(
    res
  )
  
  minSize <- 15
  maxSize <- 2000
  
  # Restrict gene sets to genes represented in the ranked vector
  hallmark_use <- lapply(
    hallmark_list,
    function(g) {
      intersect(
        g,
        names(stats)
      )
    }
  )
  
  hallmark_use <- hallmark_use[
    lengths(hallmark_use) >= minSize &
      lengths(hallmark_use) <= maxSize
  ]
  
  reactome_use <- lapply(
    reactome_list,
    function(g) {
      intersect(
        g,
        names(stats)
      )
    }
  )
  
  reactome_use <- reactome_use[
    lengths(reactome_use) >= minSize &
      lengths(reactome_use) <= maxSize
  ]
  
  fg_h <- fgsea::fgseaMultilevel(
    pathways = hallmark_use,
    stats = stats,
    eps = 0
  ) %>%
    arrange(
      padj,
      desc(NES)
    ) %>%
    mutate(
      collection = "HALLMARK"
    )
  
  fg_r <- fgsea::fgseaMultilevel(
    pathways = reactome_use,
    stats = stats,
    eps = 0
  ) %>%
    arrange(
      padj,
      desc(NES)
    ) %>%
    mutate(
      collection = "REACTOME"
    )
  
  fg_all <- bind_rows(
    fg_h,
    fg_r
  )
  
  readr::write_csv(
    fg_all,
    output_file
  )
  
  fg_all
}


# =============================================================================
# Part 2: prepare mouse Hallmark and Reactome gene sets
# =============================================================================

msig_mouse <- msigdbr::msigdbr(
  species = "Mus musculus"
)

# Support both older and newer msigdbr column nomenclature
col_cat <- if (
  "gs_cat" %in% names(msig_mouse)
) {
  "gs_cat"
} else {
  "gs_collection"
}

col_sub <- if (
  "gs_subcat" %in% names(msig_mouse)
) {
  "gs_subcat"
} else {
  "gs_subcollection"
}


hallmark_df <- msig_mouse %>%
  dplyr::filter(
    .data[[col_cat]] == "H"
  ) %>%
  dplyr::select(
    gs_name,
    gene_symbol
  )

reactome_df <- msig_mouse %>%
  dplyr::filter(
    .data[[col_cat]] == "C2",
    .data[[col_sub]] == "CP:REACTOME"
  ) %>%
  dplyr::select(
    gs_name,
    gene_symbol
  )

hallmark_list <- split(
  hallmark_df$gene_symbol,
  hallmark_df$gs_name
)

reactome_list <- split(
  reactome_df$gene_symbol,
  reactome_df$gs_name
)

# Ranked vectors were uppercased in the original analysis
hallmark_list <- lapply(
  hallmark_list,
  toupper
)

reactome_list <- lapply(
  reactome_list,
  toupper
)


# =============================================================================
# Part 3: FAT-MASH vs chow
# =============================================================================

# -----------------------------------------------------------------------------
# Hepatocytes
# -----------------------------------------------------------------------------

pb <- create_pseudobulk(
  object_file = "CCl4_RT_hepatocytes_RNAonly.rds",
  counts_output = "CCl4_hepatocytes_pseudobulk_counts.rds",
  metadata_output = "CCl4_hepatocytes_pseudobulk_metadata.csv"
)

res_CCl4_hepatocytes <- run_deseq2(
  pb_counts = pb$counts,
  pb_meta = pb$metadata,
  model_condition = "CCl4_model",
  output_file = "DESeq2.CCl4model.vs.RTchow.hepatocytes.txt"
)

fg_CCl4_hepatocytes <- run_fgsea(
  res = res_CCl4_hepatocytes,
  hallmark_list = hallmark_list,
  reactome_list = reactome_list,
  output_file = "CCl4vsControl_hepatocytes_fgsea.csv"
)

rm(pb)
gc()


# -----------------------------------------------------------------------------
# Endothelial cells
# -----------------------------------------------------------------------------

pb <- create_pseudobulk(
  object_file = "CCl4_RT_endothelial_RNAonly.rds",
  counts_output = "CCl4_endothelial_pseudobulk_counts.rds",
  metadata_output = "CCl4_endothelial_pseudobulk_metadata.csv"
)

res_CCl4_endothelial <- run_deseq2(
  pb_counts = pb$counts,
  pb_meta = pb$metadata,
  model_condition = "CCl4_model",
  output_file = "DESeq2.CCl4model.vs.RTchow.endothelial.txt"
)

fg_CCl4_endothelial <- run_fgsea(
  res = res_CCl4_endothelial,
  hallmark_list = hallmark_list,
  reactome_list = reactome_list,
  output_file = "CCl4vsControl_endo_fgsea.csv"
)

rm(pb)
gc()


# -----------------------------------------------------------------------------
# Macrophages
# -----------------------------------------------------------------------------

pb <- create_pseudobulk(
  object_file = "CCl4_RT_macrophages_RNAonly.rds",
  counts_output = "CCl4_macrophages_pseudobulk_counts.rds",
  metadata_output = "CCl4_macrophages_pseudobulk_metadata.csv"
)

res_CCl4_macrophages <- run_deseq2(
  pb_counts = pb$counts,
  pb_meta = pb$metadata,
  model_condition = "CCl4_model",
  output_file = "DESeq2.CCl4model.vs.RTchow.macrophage.txt"
)

fg_CCl4_macrophages <- run_fgsea(
  res = res_CCl4_macrophages,
  hallmark_list = hallmark_list,
  reactome_list = reactome_list,
  output_file = "CCl4vsControl_macro_fgsea.csv"
)

rm(pb)
gc()


# -----------------------------------------------------------------------------
# HSCs
# -----------------------------------------------------------------------------

pb <- create_pseudobulk(
  object_file = "CCl4_RT_HSC_RNAonly.rds",
  counts_output = "CCl4_hscs_pseudobulk_counts.rds",
  metadata_output = "CCl4_hscs_pseudobulk_metadata.csv"
)

res_CCl4_HSC <- run_deseq2(
  pb_counts = pb$counts,
  pb_meta = pb$metadata,
  model_condition = "CCl4_model",
  output_file = "DESeq2.CCl4model.vs.RTchow.hsc.txt"
)

fg_CCl4_HSC <- run_fgsea(
  res = res_CCl4_HSC,
  hallmark_list = hallmark_list,
  reactome_list = reactome_list,
  output_file = "CCl4vsControl_hsc_fgsea.csv"
)

rm(pb)
gc()


# =============================================================================
# Part 4: HOT-MASH vs chow
# =============================================================================

# -----------------------------------------------------------------------------
# Hepatocytes
# -----------------------------------------------------------------------------

pb <- create_pseudobulk(
  object_file = "DEN_RT_hepatocytes_RNAonly.rds",
  counts_output = "DEN_hepatocytes_pseudobulk_counts.rds",
  metadata_output = "DEN_hepatocytes_pseudobulk_metadata.csv"
)

res_DEN_hepatocytes <- run_deseq2(
  pb_counts = pb$counts,
  pb_meta = pb$metadata,
  model_condition = "DEN_model",
  output_file = "DESeq2.DENmodel.vs.RTchow.hepatocytes.txt"
)

fg_DEN_hepatocytes <- run_fgsea(
  res = res_DEN_hepatocytes,
  hallmark_list = hallmark_list,
  reactome_list = reactome_list,
  output_file = "DENvsControl_hepatocytes_fgsea.csv"
)

rm(pb)
gc()


# -----------------------------------------------------------------------------
# Endothelial cells
# -----------------------------------------------------------------------------

pb <- create_pseudobulk(
  object_file = "DEN_RT_endothelial_RNAonly.rds",
  counts_output = "DEN_endothelial_pseudobulk_counts.rds",
  metadata_output = "DEN_endothelial_pseudobulk_metadata.csv"
)

res_DEN_endothelial <- run_deseq2(
  pb_counts = pb$counts,
  pb_meta = pb$metadata,
  model_condition = "DEN_model",
  output_file = "DESeq2.DENmodel.vs.RTchow.endothelial.txt"
)

fg_DEN_endothelial <- run_fgsea(
  res = res_DEN_endothelial,
  hallmark_list = hallmark_list,
  reactome_list = reactome_list,
  output_file = "DENvsControl_endo_fgsea.csv"
)

rm(pb)
gc()


# -----------------------------------------------------------------------------
# Macrophages
# -----------------------------------------------------------------------------

pb <- create_pseudobulk(
  object_file = "DEN_RT_macrophages_RNAonly.rds",
  counts_output = "DEN_macrophages_pseudobulk_counts.rds",
  metadata_output = "DEN_macrophages_pseudobulk_metadata.csv"
)

res_DEN_macrophages <- run_deseq2(
  pb_counts = pb$counts,
  pb_meta = pb$metadata,
  model_condition = "DEN_model",
  output_file = "DESeq2.DENmodel.vs.RTchow.macrophage.txt"
)

fg_DEN_macrophages <- run_fgsea(
  res = res_DEN_macrophages,
  hallmark_list = hallmark_list,
  reactome_list = reactome_list,
  output_file = "DENvsControl_macro_fgsea.csv"
)

rm(pb)
gc()


# -----------------------------------------------------------------------------
# HSCs
# -----------------------------------------------------------------------------

pb <- create_pseudobulk(
  object_file = "DEN_RT_HSC_RNAonly.rds",
  counts_output = "DEN_hscs_pseudobulk_counts.rds",
  metadata_output = "DEN_hscs_pseudobulk_metadata.csv"
)

res_DEN_HSC <- run_deseq2(
  pb_counts = pb$counts,
  pb_meta = pb$metadata,
  model_condition = "DEN_model",
  output_file = "DESeq2.DENmodel.vs.RTchow.hsc.txt"
)

fg_DEN_HSC <- run_fgsea(
  res = res_DEN_HSC,
  hallmark_list = hallmark_list,
  reactome_list = reactome_list,
  output_file = "DENvsControl_hsc_fgsea.csv"
)

rm(pb)
gc()
