# Model-vs-model pseudobulk differential expression and fGSEA
#
# Supports:
#   Figure 3A
#   Figure 6A
#
# Input lineage objects are generated by 07_create_lineage_objects.R.
#
# Comparison:
#   HOT-MASH vs FAT-MASH
#
# Lineages:
#   Hepatocytes
#   Endothelial cells
#   Macrophages
#   HSCs
#   Malignant hepatocytes (cluster 13)
#
# Internal condition nomenclature retained from the original analysis:
#   CCl4_model = FAT-MASH
#   DEN_model  = HOT-MASH
#
# Pseudobulk counts are generated by summing raw RNA counts per mouse and
# analyzed with DESeq2.
#
# In the original analysis, fGSEA .rnk files were prepared manually from the
# DESeq2 Wald statistic (`stat`). Here the same ranked vectors are generated
# directly from the DESeq2 results.

library(Seurat)
library(Matrix)
library(DESeq2)
library(fgsea)
library(msigdbr)
library(dplyr)
library(tibble)
library(readr)


# =============================================================================
# Part 1: helper functions
# =============================================================================

# -----------------------------------------------------------------------------
# Pseudobulk raw RNA counts by mouse
# -----------------------------------------------------------------------------

create_pseudobulk <- function(
    object_file,
    counts_output,
    metadata_output
) {

  obj <- readRDS(object_file)

  DefaultAssay(obj) <- "RNA"

  cts <- GetAssayData(
    obj,
    assay = "RNA",
    layer = "counts"
  )

  sample_ids <- obj$sample_id

  stopifnot(
    length(sample_ids) == ncol(cts)
  )

  # Sum raw counts across cells from the same mouse
  pb_counts <- sapply(
    unique(sample_ids),
    function(sid) {
      Matrix::rowSums(
        cts[
          ,
          sample_ids == sid,
          drop = FALSE
        ]
      )
    }
  )

  pb_counts <- as.matrix(pb_counts)

  # Sample-level metadata
  pb_meta <- obj@meta.data %>%
    as.data.frame() %>%
    dplyr::group_by(sample_id) %>%
    dplyr::summarise(
      condition = dplyr::first(condition),
      role = dplyr::first(role),
      n_cells = dplyr::n(),
      .groups = "drop"
    )

  # Match metadata order to pseudobulk matrix
  pb_meta <- pb_meta[
    match(
      colnames(pb_counts),
      pb_meta$sample_id
    ),
  ]

  pb_meta <- as.data.frame(pb_meta)

  rownames(pb_meta) <- pb_meta$sample_id

  stopifnot(
    identical(
      colnames(pb_counts),
      rownames(pb_meta)
    )
  )

  # Basic pseudobulk QC
  print(colSums(pb_counts))
  print(colSums(pb_counts > 0))
  print(pb_meta$n_cells)

  saveRDS(
    pb_counts,
    counts_output
  )

  write.csv(
    pb_meta,
    metadata_output,
    row.names = TRUE
  )

  rm(obj, cts)
  gc()

  list(
    counts = pb_counts,
    metadata = pb_meta
  )
}


# -----------------------------------------------------------------------------
# DESeq2 HOT-MASH vs FAT-MASH analysis
# -----------------------------------------------------------------------------

run_deseq2 <- function(
    pb_counts,
    pb_meta,
    output_file
) {

  pb_meta <- pb_meta[
    colnames(pb_counts),
    ,
    drop = FALSE
  ]

  stopifnot(
    identical(
      rownames(pb_meta),
      colnames(pb_counts)
    )
  )

  # FAT-MASH is the reference level
  pb_meta$condition <- factor(
    pb_meta$condition,
    levels = c(
      "CCl4_model",
      "DEN_model"
    )
  )

  # Original prefilter:
  # at least 10 counts in at least 2 samples
  keep <- rowSums(
    pb_counts >= 10
  ) >= 2

  pb_counts_filt <- pb_counts[
    keep,
  ]

  dds <- DESeqDataSetFromMatrix(
    countData = round(pb_counts_filt),
    colData = pb_meta,
    design = ~ condition
  )

  dds <- DESeq(dds)

  res <- results(
    dds,
    contrast = c(
      "condition",
      "DEN_model",
      "CCl4_model"
    ),
    alpha = 0.05
  )

  print(summary(res))

  write.table(
    res,
    output_file,
    sep = "\t"
  )

  res
}


# -----------------------------------------------------------------------------
# Convert DESeq2 Wald statistic to ranked vector for fGSEA
# -----------------------------------------------------------------------------

make_rank_vector <- function(res) {

  rank_df <- data.frame(
    GENE = rownames(res),
    RANK = res$stat,
    stringsAsFactors = FALSE
  ) %>%
    dplyr::mutate(
      GENE = toupper(
        trimws(GENE)
      )
    ) %>%
    dplyr::filter(
      !is.na(GENE),
      is.finite(RANK)
    ) %>%
    dplyr::group_by(GENE) %>%
    dplyr::slice_max(
      order_by = abs(RANK),
      n = 1,
      with_ties = FALSE
    ) %>%
    dplyr::ungroup()

  stats <- rank_df$RANK

  names(stats) <- rank_df$GENE

  stats <- stats[
    order(
      stats,
      decreasing = TRUE
    )
  ]

  stats
}


# -----------------------------------------------------------------------------
# fGSEA using Hallmark and Reactome gene sets
# -----------------------------------------------------------------------------

run_fgsea <- function(
    res,
    hallmark_list,
    reactome_list,
    output_file
) {

  stats <- make_rank_vector(res)

  minSize <- 15
  maxSize <- 2000

  hallmark_use <- lapply(
    hallmark_list,
    function(g) {
      intersect(
        g,
        names(stats)
      )
    }
  )

  hallmark_use <- hallmark_use[
    lengths(hallmark_use) >= minSize &
      lengths(hallmark_use) <= maxSize
  ]

  reactome_use <- lapply(
    reactome_list,
    function(g) {
      intersect(
        g,
        names(stats)
      )
    }
  )

  reactome_use <- reactome_use[
    lengths(reactome_use) >= minSize &
      lengths(reactome_use) <= maxSize
  ]

  fg_h <- fgsea::fgseaMultilevel(
    pathways = hallmark_use,
    stats = stats,
    eps = 0
  ) %>%
    dplyr::arrange(
      padj,
      dplyr::desc(NES)
    ) %>%
    dplyr::mutate(
      collection = "HALLMARK"
    )

  fg_r <- fgsea::fgseaMultilevel(
    pathways = reactome_use,
    stats = stats,
    eps = 0
  ) %>%
    dplyr::arrange(
      padj,
      dplyr::desc(NES)
    ) %>%
    dplyr::mutate(
      collection = "REACTOME"
    )

  fg_all <- dplyr::bind_rows(
    fg_h,
    fg_r
  )

  readr::write_csv(
    fg_all,
    output_file
  )

  fg_all
}


# =============================================================================
# Part 2: prepare mouse Hallmark and Reactome gene sets
# =============================================================================

msig_mouse <- msigdbr::msigdbr(
  species = "Mus musculus"
)

# Support both older and newer msigdbr column nomenclature
col_cat <- if (
  "gs_cat" %in% names(msig_mouse)
) {
  "gs_cat"
} else {
  "gs_collection"
}

col_sub <- if (
  "gs_subcat" %in% names(msig_mouse)
) {
  "gs_subcat"
} else {
  "gs_subcollection"
}


hallmark_df <- msig_mouse %>%
  dplyr::filter(
    .data[[col_cat]] == "H"
  ) %>%
  dplyr::select(
    gs_name,
    gene_symbol
  )


reactome_df <- msig_mouse %>%
  dplyr::filter(
    .data[[col_cat]] == "C2",
    .data[[col_sub]] == "CP:REACTOME"
  ) %>%
  dplyr::select(
    gs_name,
    gene_symbol
  )


hallmark_list <- split(
  hallmark_df$gene_symbol,
  hallmark_df$gs_name
)

reactome_list <- split(
  reactome_df$gene_symbol,
  reactome_df$gs_name
)

# Ranked vectors were uppercased in the original analysis
hallmark_list <- lapply(
  hallmark_list,
  toupper
)

reactome_list <- lapply(
  reactome_list,
  toupper
)


# =============================================================================
# Part 3: shared lineage model-vs-model comparisons
# =============================================================================

# -----------------------------------------------------------------------------
# Hepatocytes
# -----------------------------------------------------------------------------

pb <- create_pseudobulk(
  object_file = "Models_hepatocytes_RNAonly.rds",
  counts_output = "models_hepatocytes_pseudobulk_counts.rds",
  metadata_output = "models_hepatocytes_pseudobulk_metadata.csv"
)

res_hepatocytes <- run_deseq2(
  pb_counts = pb$counts,
  pb_meta = pb$metadata,
  output_file = "DESeq2.DENmodel.vs.CCl4model.hepatocytes.txt"
)

fg_hepatocytes <- run_fgsea(
  res = res_hepatocytes,
  hallmark_list = hallmark_list,
  reactome_list = reactome_list,
  output_file = "DENvsCCl4_hepatocytes_fgsea.csv"
)

rm(pb)
gc()


# -----------------------------------------------------------------------------
# Endothelial cells
# -----------------------------------------------------------------------------

pb <- create_pseudobulk(
  object_file = "Models_endothelial_RNAonly.rds",
  counts_output = "models_endothelial_pseudobulk_counts.rds",
  metadata_output = "models_endothelial_pseudobulk_metadata.csv"
)

res_endothelial <- run_deseq2(
  pb_counts = pb$counts,
  pb_meta = pb$metadata,
  output_file = "DESeq2.DENmodel.vs.CCl4model.endothelial.txt"
)

fg_endothelial <- run_fgsea(
  res = res_endothelial,
  hallmark_list = hallmark_list,
  reactome_list = reactome_list,
  output_file = "DENvsCCl4_endo_fgsea.csv"
)

rm(pb)
gc()


# -----------------------------------------------------------------------------
# Macrophages
# -----------------------------------------------------------------------------

pb <- create_pseudobulk(
  object_file = "Models_macrophages_RNAonly.rds",
  counts_output = "models_macrophages_pseudobulk_counts.rds",
  metadata_output = "models_macrophages_pseudobulk_metadata.csv"
)

res_macrophages <- run_deseq2(
  pb_counts = pb$counts,
  pb_meta = pb$metadata,
  output_file = "DESeq2.DENmodel.vs.CCl4model.macrophage.txt"
)

fg_macrophages <- run_fgsea(
  res = res_macrophages,
  hallmark_list = hallmark_list,
  reactome_list = reactome_list,
  output_file = "DENvsCCl4_macro_fgsea.csv"
)

rm(pb)
gc()


# -----------------------------------------------------------------------------
# HSCs
# -----------------------------------------------------------------------------

pb <- create_pseudobulk(
  object_file = "Models_HSC_RNAonly.rds",
  counts_output = "models_hscs_pseudobulk_counts.rds",
  metadata_output = "models_hscs_pseudobulk_metadata.csv"
)

res_HSC <- run_deseq2(
  pb_counts = pb$counts,
  pb_meta = pb$metadata,
  output_file = "DESeq2.DENmodel.vs.CCl4model.hsc.txt"
)

fg_HSC <- run_fgsea(
  res = res_HSC,
  hallmark_list = hallmark_list,
  reactome_list = reactome_list,
  output_file = "DENvsCCl4_hsc_fgsea.csv"
)

rm(pb)
gc()


# =============================================================================
# Part 4: malignant-hepatocyte model-vs-model comparison
# =============================================================================

# Cluster 13 malignant hepatocytes are analyzed separately from the shared
# hepatocyte lineage. This comparison supports the tumor-cell fGSEA shown
# in Figure 3A.

pb <- create_pseudobulk(
  object_file = "Models_malignantHeps_RNAonly.rds",
  counts_output = "models_malignantHeps_pseudobulk_counts.rds",
  metadata_output = "models_malignantHeps_pseudobulk_metadata.csv"
)

res_malignantHeps <- run_deseq2(
  pb_counts = pb$counts,
  pb_meta = pb$metadata,
  output_file = "DESeq2.DENmodel.vs.CCl4model.malignantHeps.txt"
)

fg_malignantHeps <- run_fgsea(
  res = res_malignantHeps,
  hallmark_list = hallmark_list,
  reactome_list = reactome_list,
  output_file = "DENvsCCl4_malignantHeps_fgsea.csv"
)

rm(pb)
gc()
