# fGSEA biological-theme annotation and plotting
#
# Supports:
#   Figure 3A - tumor-cell model-vs-model fGSEA summary
#   Figure 5A - model-vs-chow fGSEA summaries
#   Figure 6A - model-vs-model fGSEA summary
#
# Raw fGSEA results are generated by:
#   08_model_vs_control_pseudobulk_DE_fGSEA.R
#   09_model_vs_model_pseudobulk_DE_fGSEA.R
#
# Significant Hallmark and Reactome pathways were grouped into broader
# biological themes using keyword matching, followed by manual review.
# The final theme-level NES values and direction labels used for plotting
# are retained explicitly below.
#
# Figures 5B-C and 6B were generated separately in Cytoscape using
# EnrichmentMap from the significant Hallmark fGSEA results.
#
# Final manuscript panels included minor manual formatting outside R.

library(dplyr)
library(tidyr)
library(stringr)
library(tibble)
library(readr)
library(ggplot2)


# =============================================================================
# Part 1: biological theme dictionary
# =============================================================================

theme_dict <- list(
  
  ECM_Fibrosis_Angiogenic_Remodeling = c(
    "EXTRACELLULAR_MATRIX", "ECM", "COLLAGEN", "MATRIX_ORGANIZATION",
    "COLLAGEN_FORMATION", "COLLAGEN_DEGRADATION", "INTEGRIN",
    "MATRIX_METALLOPROTEIN", "BASEMENT_MEMBRANE",
    "EPITHELIAL_MESENCHYMAL_TRANSITION", "EMT",
    "FIBROSIS", "TGF_BETA",
    "ANGIOGENESIS", "VEGF", "ANGIOPOIETIN", "ENDOTHELIAL"
  ),
  
  Hemostasis_Coagulation = c(
    "HEMOSTASIS", "COAGULATION", "PLATELET",
    "FIBRIN", "FIBRINOLYSIS", "THROMBIN",
    "CLOTTING", "PROTHROMBIN", "VON_WILLEBRAND"
  ),
  
  Myeloid_Inflammation_NFkB_Inflammasome = c(
    "NFKB", "TNFA",
    "INFLAMMASOME", "NLRP3", "PYROPTOSIS",
    "TOLL_LIKE", "TLR", "NOD_LIKE", "MYD88",
    "CHEMOKINE", "CCR", "CXCR",
    "MACROPHAGE", "MONOCYTE", "NEUTROPHIL",
    "PHAGOCYTOSIS", "COMPLEMENT", "INFLAMMATORY_RESPONSE",
    "INTERLEUKIN", "CYTOKINE", "IL6", "JAK_STAT3", "NLR",
    "CSF1", "GM_CSF"
  ),
  
  Interferon_Antigen_Presentation = c(
    "INTERFERON", "IFN",
    "ANTIGEN_PRESENTATION", "CROSS_PRESENTATION",
    "MHC", "HLA", "IMMUNOPROTEASOME", "ANTIGEN_PROCESSING"
  ),
  
  Lymphoid_Immunity_Checkpoints_Exhaustion = c(
    "T_CELL", "TCR",
    "B_CELL", "BCR",
    "PD_1", "PD1", "CTLA4",
    "CO_STIMULATION", "IMMUNE_CHECKPOINT",
    "EXHAUSTION", "CYTOTOXIC", "GRANZYME",
    "NATURAL_KILLER", "IL2_STAT5",
    "LYMPHOID", "ADAPTIVE_IMMUN", "ALLOGRAFT_REJECTION"
  ),
  
  Proliferation_Cell_Cycle = c(
    "CELL_CYCLE", "E2F", "G2M", "MITOTIC",
    "DNA_REPLICATION", "S_PHASE", "M_PHASE", "CHECKPOINT",
    "SPINDLE", "PROMETAPHASE", "AURKA", "CYCLIN", "CHROMATID"
  ),
  
  Gene_Expression_Machinery = c(
    "RIBOSOME", "RIBOSOMAL", "SPLICEOSOME", "_TRANSLATION_",
    "RNA_POLYMERASE", "RNA_PROCESSING", "RNA_SPLICING",
    "MRNA", "EIF", "CAP-BINDING", "SRP", "REACTOME_TRANSLATION"
  ),
  
  Stress_UPR_DNA_Damage_Cell_Death = c(
    "UNFOLDED_PROTEIN_RESPONSE", "ER_STRESS",
    "DNA_DAMAGE", "GENOME_INSTABILITY",
    "APOPTOSIS", "SENESCENCE", "HYPOXIA", "CELL_DEATH",
    "UV_RESPONSE", "IRE1", "ERQC", "CALNEXIN",
    "CALRETICULIN", "CHEMICAL_STRESS", "UNFOLDED_PROTEIN"
  ),
  
  Mitochondrial_OXPHOS_Redox = c(
    "MITOCHONDRIAL",
    "OXIDATIVE_PHOSPHORYLATION", "RESPIRATORY_ELECTRON_TRANSPORT",
    "ELECTRON_TRANSPORT_CHAIN", "TCA_CYCLE", "CITRIC_ACID_CYCLE",
    "ATP_SYNTHASE", "ATP_SYNTHESIS", "ATP_PRODUCTION",
    "REACTIVE_OXYGEN_SPECIES",
    "MITOCHONDRIAL_TRANSLATION",
    "MITOCHONDRIAL_PROTEIN_DEGRADATION",
    "COMPLEX_I_", "COMPLEX_III", "COMPLEX_IV", "CRISTAE",
    "FORMATION_OF_ATP"
  ),
  
  Lipid_Metabolism_and_Lipotoxicity = c(
    "FATTY_ACID", "BETA_OXIDATION",
    "PEROXISOME",
    "PPAR",
    "TRIGLYCERIDE", "LIPID_DROPLET", "LIPOPROTEIN",
    "CERAMIDE", "SPHINGOLIPID", "SPHINGOMYELIN",
    "PHOSPHOLIPID", "ADIPOGENESIS", "PEROXISOMAL_LIPID",
    "FATTY_ACYL_COA", "METABOLISM_OF_LIPIDS"
  ),
  
  Sterol_Steroid_Cholesterol = c(
    "CHOLESTEROL", "STEROL", "STEROID",
    "SREBP", "MEVALONATE"
  ),
  
  BileAcid_FXR_TGR5 = c(
    "BILE_ACID", "BILE_SALT",
    "FXR", "TGR5", "CHOLESTASIS", "BILIARY"
  ),
  
  Xenobiotic_Detoxification = c(
    "XENOBIOTIC", "DRUG_METABOLISM",
    "BIOLOGICAL_OXIDATIONS",
    "CYTOCHROME_P450",
    "PHASE_I_", "PHASE_II_",
    "GLUCURONIDATION", "SULFATION",
    "GLUTATHIONE_CONJUGATION",
    "NRF2", "ADME", "NFE2L2"
  ),
  
  PI3K_AKT_Signaling = c(
    "PI3K", "AKT"
  ),
  
  mTOR_and_Glycolysis = c(
    "MTOR", "MTORC1", "RAPAMYCIN",
    "GLYCOLYSIS", "GLUCOSE",
    "GLUCONEOGENESIS", "PENTOSE_PHOSPHATE",
    "FRUCTOSE", "INSULIN"
  ),
  
  Autophagy_Lysosome_Lipophagy = c(
    "AUTOPHAGY", "MACROAUTOPHAGY",
    "CHAPERONE_MEDIATED_AUTOPHAGY",
    "AUTOPHAGOSOME",
    "LYSOSOME", "LYSOSOMAL",
    "LIPOPHAGY", "MICROLIPOPHAGY",
    "MITOPHAGY"
  ),
  
  RTK_RAS_MAPK_Signaling = c(
    "RTK", "RECEPTOR_TYROSINE_KINASE",
    "EGFR", "ERBB",
    "FGFR", "PDGFR", "MEK",
    "MAPK", "ERK", "KRAS", "PDGF"
  ),
  
  Developmental_Oncogenic_WNT_NOTCH_HIPPO_HH = c(
    "WNT", "BETA_CATENIN",
    "NOTCH",
    "HIPPO", "YAP", "TEAD",
    "HEDGEHOG", "GLI"
  ),
  
  Ferroptosis_Iron_Metabolism = c(
    "FERROPTOSIS",
    "IRON", "FERRITIN", "TRANSFERRIN",
    "HEPCIDIN",
    "LIPID_PEROXIDATION"
  )
)


# =============================================================================
# Part 2: annotate significant fGSEA pathways with biological themes
# =============================================================================

annotate_gsea_themes <- function(
    df,
    theme_dict,
    pathway_col = "pathway"
) {
  
  required_cols <- c(
    pathway_col,
    "NES",
    "p_adj"
  )
  
  missing_cols <- setdiff(
    required_cols,
    colnames(df)
  )
  
  if (length(missing_cols) > 0) {
    stop(
      "Missing required columns: ",
      paste(
        missing_cols,
        collapse = ", "
      )
    )
  }
  
  df2 <- df %>%
    tibble::as_tibble() %>%
    dplyr::mutate(
      .row_id = dplyr::row_number()
    )
  
  dict_long <- tibble::enframe(
    theme_dict,
    name = "theme",
    value = "keyword"
  ) %>%
    tidyr::unnest_longer(keyword) %>%
    dplyr::mutate(
      keyword = as.character(keyword)
    )
  
  # Cartesian join followed by keyword matching.
  # A pathway can match more than one biological theme.
  matches <- df2 %>%
    dplyr::select(
      .row_id,
      dplyr::all_of(pathway_col)
    ) %>%
    tidyr::crossing(
      dict_long
    ) %>%
    dplyr::mutate(
      .matched = stringr::str_detect(
        .data[[pathway_col]],
        stringr::regex(
          keyword,
          ignore_case = TRUE
        )
      )
    ) %>%
    dplyr::filter(
      .matched
    ) %>%
    dplyr::transmute(
      .row_id,
      theme,
      matched_keyword = keyword
    )
  
  # Keep unmatched pathways with NA theme/keyword.
  df2 %>%
    dplyr::left_join(
      matches,
      by = ".row_id"
    ) %>%
    dplyr::select(
      -.row_id
    )
}


# -----------------------------------------------------------------------------
# Read significant pathways from fGSEA outputs generated by scripts 08 and 09
#
# In the original working script, significant pathway names, NES values and
# adjusted P values were copied into R data.frames before theme annotation.
# Here the same information is read directly from the deposited fGSEA outputs.
# -----------------------------------------------------------------------------

fgsea_files <- c(
  
  CCl4_heps =
    "CCl4vsControl_hepatocytes_fgsea.csv",
  
  CCl4_endo =
    "CCl4vsControl_endo_fgsea.csv",
  
  CCl4_macro =
    "CCl4vsControl_macro_fgsea.csv",
  
  CCl4_hsc =
    "CCl4vsControl_hsc_fgsea.csv",
  
  DEN_heps =
    "DENvsControl_hepatocytes_fgsea.csv",
  
  DEN_endo =
    "DENvsControl_endo_fgsea.csv",
  
  DEN_macro =
    "DENvsControl_macro_fgsea.csv",
  
  DEN_hsc =
    "DENvsControl_hsc_fgsea.csv",
  
  models_heps =
    "DENvsCCl4_hepatocytes_fgsea.csv",
  
  models_endo =
    "DENvsCCl4_endo_fgsea.csv",
  
  models_macro =
    "DENvsCCl4_macro_fgsea.csv",
  
  models_hsc =
    "DENvsCCl4_hsc_fgsea.csv",
  
  models_tumorCells =
    "DENvsCCl4_malignantHeps_fgsea.csv"
)


collapsed_results <- list()

for (nm in names(fgsea_files)) {
  
  fg <- readr::read_csv(
    fgsea_files[[nm]],
    show_col_types = FALSE
  ) %>%
    dplyr::filter(
      !is.na(padj),
      padj < 0.05
    ) %>%
    dplyr::transmute(
      pathway = pathway,
      NES = NES,
      p_adj = padj
    )
  
  annotated_df <- annotate_gsea_themes(
    df = fg,
    theme_dict = theme_dict
  )
  
  collapsed_results[[nm]] <- annotated_df
  
  write.table(
    annotated_df,
    file = paste0(
      "fgsea_",
      nm,
      "_collapsed.txt"
    ),
    row.names = FALSE,
    sep = "\t",
    quote = FALSE
  )
}


# =============================================================================
# Part 3: final theme-level summaries used for manuscript dot plots
# =============================================================================

# These theme-level values and direction labels were manually curated from
# the annotated significant pathways during the original analysis.
#
# Zero was used in the original working tables to indicate no retained
# theme-level signal and is converted to NA below.

theme_order <- c(
  "Gene Expression Machinery",
  "Cell Cycle & Proliferation",
  "RTK-MAPK Signaling",
  "Developmental Signaling (WNT NOTCH HH)",
  "Coagulation & Hemostasis",
  "ECM Remodeling & Fibrosis",
  "Adaptive Immunity & Immune Checkpoints",
  "Interferon Signaling & Antigen Presentation",
  "Myeloid Inflammation & Innate Immune Signaling",
  "Autophagy & Lysosomal Degradation",
  "Iron Metabolism & Ferroptosis",
  "Stress Response & Cell Fate",
  "PI3K–AKT Signaling",
  "Glucose Metabolism & mTOR Signaling",
  "Xenobiotic Metabolism & Detoxification",
  "Mitochondrial Function & OXPHOS",
  "Bile Acid Metabolism & Signaling",
  "Cholesterol Metabolism",
  "Fatty Acid & Lipid Metabolism"
)

cell_order <- c(
  "Hepatocytes",
  "Endothelial",
  "Macrophages",
  "HSCs"
)


# -----------------------------------------------------------------------------
# CCl4 model vs chow
# -----------------------------------------------------------------------------

CCl4_mat <- tibble::tribble(
  ~Theme, ~Hepatocytes, ~Endothelial, ~Macrophages, ~HSCs,
  "Fatty Acid & Lipid Metabolism", -2.571873301, -2.675421135, -2.553895294, -2.551458203,
  "Cholesterol Metabolism", -2.857669096, -3.011762527, -2.845033426, -2.784043742,
  "Bile Acid Metabolism & Signaling", -2.66859185, -2.919481007, -2.808355852, -2.751102422,
  "Mitochondrial Function & OXPHOS", -2.762853389, -2.706293331, -2.59414202, -2.574987594,
  "Xenobiotic Metabolism & Detoxification", -2.519979793, -2.875900229, -2.754539025, -2.791569289,
  "Glucose Metabolism & mTOR Signaling", -2.098816464, -2.583125632, -2.661495822, -2.061467528,
  "PI3K–AKT Signaling", 2.101904323, 1.889310824, 2.286814939, 0,
  "Stress Response & Cell Fate", 1.772120355, 1.814439118, 1.684571299, 0,
  "Iron Metabolism & Ferroptosis", 0, 0, 0, 0,
  "Autophagy & Lysosomal Degradation", -2.220906643, -1.785188665, -1.631719951, 0,
  "Myeloid Inflammation & Innate Immune Signaling", 2.449787403, 2.251823964, 2.703401325, 2.089138754,
  "Interferon Signaling & Antigen Presentation", 0, 2.063321755, 2.476953044, 0,
  "Adaptive Immunity & Immune Checkpoints", 2.093161205, 1.997143715, 2.564069495, 1.792775316,
  "ECM Remodeling & Fibrosis", 1.957941285, 2.211686481, 2.405040857, 2.869295697,
  "Coagulation & Hemostasis", -2.335022982, -2.43625966, 0, -2.448747602,
  "Developmental Signaling (WNT NOTCH HH)", -2.206301379, -1.908924998, -1.739584674, -1.800474496,
  "RTK-MAPK Signaling", 2.040934915, 2.106850312, 2.332013825, 2.389975384,
  "Cell Cycle & Proliferation", 2.177641779, 2.286929845, 1.934086799, 2.304607649,
  "Gene Expression Machinery", -2.221340925, 0, -1.900231434, 1.745120763
)

CCl4_direction <- tibble::tribble(
  ~Theme, ~Hepatocytes, ~Endothelial, ~Macrophages, ~HSCs,
  "Fatty Acid & Lipid Metabolism", "down", "down", "down", "down",
  "Cholesterol Metabolism", "down", "down", "down", "down",
  "Bile Acid Metabolism & Signaling", "down", "down", "down", "down",
  "Mitochondrial Function & OXPHOS", "down", "down", "down", "down",
  "Xenobiotic Metabolism & Detoxification", "down", "down", "down", "down",
  "Glucose Metabolism & mTOR Signaling", "down", "down", "down", "down",
  "PI3K–AKT Signaling", "up", "up", "up", "0",
  "Stress Response & Cell Fate", "mostly up", "mostly up", "mostly up", "0",
  "Iron Metabolism & Ferroptosis", "0", "0", "0", "0",
  "Autophagy & Lysosomal Degradation", "down", "down", "down", "0",
  "Myeloid Inflammation & Innate Immune Signaling", "mostly up", "mostly up", "mostly up", "mostly up",
  "Interferon Signaling & Antigen Presentation", "0", "up", "up", "0",
  "Adaptive Immunity & Immune Checkpoints", "up", "up", "up", "up",
  "ECM Remodeling & Fibrosis", "up", "up", "up", "up",
  "Coagulation & Hemostasis", "mostly down", "down", "0", "down",
  "Developmental Signaling (WNT NOTCH HH)", "down", "down", "down", "down",
  "RTK-MAPK Signaling", "up", "up", "up", "up",
  "Cell Cycle & Proliferation", "mostly up", "up", "up", "mostly up",
  "Gene Expression Machinery", "down", "0", "down", "mostly up"
)


# -----------------------------------------------------------------------------
# DEN model vs chow
# -----------------------------------------------------------------------------

DEN_mat <- tibble::tribble(
  ~Theme, ~Hepatocytes, ~Endothelial, ~Macrophages, ~HSCs,
  "Fatty Acid & Lipid Metabolism", -1.938840166, -2.280728039, -2.184169847, -2.581143774,
  "Cholesterol Metabolism", -2.991593569, -3.073150157, -3.053896296, -2.832451467,
  "Bile Acid Metabolism & Signaling", -2.345087173, -2.969026946, -2.769671483, -2.765040382,
  "Mitochondrial Function & OXPHOS", -2.532499965, -2.69290412, -2.661976593, -2.601886249,
  "Xenobiotic Metabolism & Detoxification", -2.248331318, -2.754539025, -2.550680992, -2.812149722,
  "Glucose Metabolism & mTOR Signaling", -1.7159095, -2.173448688, -2.450455476, -2.082776611,
  "PI3K–AKT Signaling", 1.692968508, 1.606077216, 1.936576247, 0,
  "Stress Response & Cell Fate", 1.692178967, 1.862225706, 1.651801009, 0,
  "Iron Metabolism & Ferroptosis", 0, 0, 0, 0,
  "Autophagy & Lysosomal Degradation", -1.932059065, -1.689606341, -1.89276853, -1.55906577,
  "Myeloid Inflammation & Innate Immune Signaling", 2.30828792, 2.435711481, 2.57065517, 2.102215081,
  "Interferon Signaling & Antigen Presentation", 2.236383246, 2.699872347, 2.691494532, 0,
  "Adaptive Immunity & Immune Checkpoints", 2.179882755, 2.286912031, 2.564958346, 1.761830626,
  "ECM Remodeling & Fibrosis", 1.550767833, 2.177543545, 2.167278966, 2.860473677,
  "Coagulation & Hemostasis", -2.050243615, 0, 0, -2.495973423,
  "Developmental Signaling (WNT NOTCH HH)", -1.808114582, -1.897254162, -1.978281954, -1.80345696,
  "RTK-MAPK Signaling", 2.160611593, 2.016261892, 2.114393502, 2.386615198,
  "Cell Cycle & Proliferation", 1.569174205, 1.794968228, 1.922619215, 2.29539252,
  "Gene Expression Machinery", -2.028208615, -1.766521222, -1.94975255, 1.725810376
)

DEN_direction <- tibble::tribble(
  ~Theme, ~Hepatocytes, ~Endothelial, ~Macrophages, ~HSCs,
  "Fatty Acid & Lipid Metabolism", "down", "down", "down", "down",
  "Cholesterol Metabolism", "down", "down", "down", "down",
  "Bile Acid Metabolism & Signaling", "down", "down", "down", "down",
  "Mitochondrial Function & OXPHOS", "down", "down", "down", "down",
  "Xenobiotic Metabolism & Detoxification", "down", "down", "down", "down",
  "Glucose Metabolism & mTOR Signaling", "down", "down", "down", "down",
  "PI3K–AKT Signaling", "up", "up", "up", "0",
  "Stress Response & Cell Fate", "mostly up", "mostly up", "mostly up", "0",
  "Iron Metabolism & Ferroptosis", "0", "0", "0", "0",
  "Autophagy & Lysosomal Degradation", "down", "down", "down", "down",
  "Myeloid Inflammation & Innate Immune Signaling", "up", "up", "up", "mostly up",
  "Interferon Signaling & Antigen Presentation", "up", "up", "up", "0",
  "Adaptive Immunity & Immune Checkpoints", "up", "up", "up", "up",
  "ECM Remodeling & Fibrosis", "up", "up", "up", "up",
  "Coagulation & Hemostasis", "mostly down", "0", "0", "down",
  "Developmental Signaling (WNT NOTCH HH)", "down", "down", "down", "down",
  "RTK-MAPK Signaling", "up", "up", "up", "up",
  "Cell Cycle & Proliferation", "up", "up", "up", "up",
  "Gene Expression Machinery", "down", "down", "down", "mostly up"
)


# -----------------------------------------------------------------------------
# DEN model vs CCl4 model
# Positive NES = enrichment in DEN
# Negative NES = enrichment in CCl4
# -----------------------------------------------------------------------------

models_mat <- tibble::tribble(
  ~Theme, ~Hepatocytes, ~Endothelial, ~Macrophages, ~HSCs,
  "Fatty Acid & Lipid Metabolism", 2.969276133, 2.78454313, 2.680157107, 2.754436729,
  "Cholesterol Metabolism", 2.383351514, 2.534990692, 2.506876297, 2.448154597,
  "Bile Acid Metabolism & Signaling", 2.210677761, 2.712548895, 2.862806127, 2.61354911,
  "Mitochondrial Function & OXPHOS", 2.591074536, 2.439106652, 2.539077157, 2.460533307,
  "Xenobiotic Metabolism & Detoxification", 2.354587848, 2.797523023, 2.871521019, 2.778485839,
  "Glucose Metabolism & mTOR Signaling", 2.103064243, 2.388589676, 2.126757867, 1.960007846,
  "PI3K–AKT Signaling", 0, 0, 0, 0,
  "Stress Response & Cell Fate", 0, 2.083704485, 0, 0,
  "Iron Metabolism & Ferroptosis", 1.826212483, 1.589051098, 0, 0,
  "Autophagy & Lysosomal Degradation", 1.933885443, 1.688097777, 1.831817289, 1.704318925,
  "Myeloid Inflammation & Innate Immune Signaling", 0, 0, 0, 0,
  "Interferon Signaling & Antigen Presentation", 2.017294902, 1.649117633, -2.01723843, 0,
  "Adaptive Immunity & Immune Checkpoints", 0, 0, -2.096956859, 0,
  "ECM Remodeling & Fibrosis", -1.893668461, -1.984587085, -1.93696399, -2.826051446,
  "Coagulation & Hemostasis", 2.005322871, 2.400196322, 2.189062592, 2.269125716,
  "Developmental Signaling (WNT NOTCH HH)", 2.010471561, 1.733096405, 1.719559011, 0,
  "RTK-MAPK Signaling", -1.819609404, -1.308130019, -1.966607572, -2.339996197,
  "Cell Cycle & Proliferation", -2.32300378, -2.073293146, -1.990183416, -2.422810542,
  "Gene Expression Machinery", 1.780661729, -1.533889193, 0, 1.774860574
)

models_direction <- tibble::tribble(
  ~Theme, ~Hepatocytes, ~Endothelial, ~Macrophages, ~HSCs,
  "Fatty Acid & Lipid Metabolism", "up", "up", "up", "up",
  "Cholesterol Metabolism", "up", "up", "up", "up",
  "Bile Acid Metabolism & Signaling", "up", "up", "up", "up",
  "Mitochondrial Function & OXPHOS", "up", "up", "up", "up",
  "Xenobiotic Metabolism & Detoxification", "up", "up", "up", "up",
  "Glucose Metabolism & mTOR Signaling", "up", "up", "up", "up",
  "PI3K–AKT Signaling", "0", "0", "0", "0",
  "Stress Response & Cell Fate", "0", "mostly up", "0", "0",
  "Iron Metabolism & Ferroptosis", "up", "up", "0", "0",
  "Autophagy & Lysosomal Degradation", "up", "up", "up", "up",
  "Myeloid Inflammation & Innate Immune Signaling", "0", "0", "0", "0",
  "Interferon Signaling & Antigen Presentation", "up", "up", "down", "0",
  "Adaptive Immunity & Immune Checkpoints", "0", "0", "down", "0",
  "ECM Remodeling & Fibrosis", "down", "down", "down", "down",
  "Coagulation & Hemostasis", "up", "up", "up", "up",
  "Developmental Signaling (WNT NOTCH HH)", "up", "up", "up", "0",
  "RTK-MAPK Signaling", "down", "down", "down", "down",
  "Cell Cycle & Proliferation", "down", "down", "down", "mostly down",
  "Gene Expression Machinery", "mostly up", "down", "0", "mostly up"
)


# Original zero placeholders indicate no retained theme-level signal.
CCl4_mat[CCl4_mat == 0] <- NA
DEN_mat[DEN_mat == 0] <- NA
models_mat[models_mat == 0] <- NA

CCl4_direction[CCl4_direction == "0"] <- NA
DEN_direction[DEN_direction == "0"] <- NA
models_direction[models_direction == "0"] <- NA


# =============================================================================
# Part 4: prepare shared-lineage plotting data
# =============================================================================

prepare_theme_plot_data <- function(
    nes_table,
    direction_table
) {
  
  nes_long <- nes_table %>%
    dplyr::mutate(
      Theme = factor(
        Theme,
        levels = theme_order
      )
    ) %>%
    tidyr::pivot_longer(
      cols = dplyr::all_of(cell_order),
      names_to = "CellType",
      values_to = "NES"
    ) %>%
    dplyr::filter(
      !is.na(NES)
    ) %>%
    dplyr::mutate(
      CellType = factor(
        CellType,
        levels = cell_order
      ),
      absNES = abs(NES)
    )
  
  direction_long <- direction_table %>%
    tidyr::pivot_longer(
      cols = dplyr::all_of(cell_order),
      names_to = "CellType",
      values_to = "Direction"
    )
  
  nes_long %>%
    dplyr::left_join(
      direction_long,
      by = c(
        "Theme",
        "CellType"
      )
    ) %>%
    dplyr::mutate(
      Theme = factor(
        Theme,
        levels = theme_order
      ),
      CellType = factor(
        CellType,
        levels = cell_order
      )
    )
}


CCl4_long <- prepare_theme_plot_data(
  CCl4_mat,
  CCl4_direction
)

DEN_long <- prepare_theme_plot_data(
  DEN_mat,
  DEN_direction
)

models_long <- prepare_theme_plot_data(
  models_mat,
  models_direction
)


# =============================================================================
# Part 5: shared-lineage theme dot plots
# =============================================================================

plot_theme_summary <- function(
    df,
    title
) {
  
  ggplot2::ggplot(
    df,
    ggplot2::aes(
      x = CellType,
      y = Theme
    )
  ) +
    ggplot2::geom_point(
      ggplot2::aes(
        size = absNES,
        color = Direction
      ),
      alpha = 0.95
    ) +
    ggplot2::scale_color_manual(
      values = c(
        "up" = "red",
        "down" = "blue",
        "mostly up" = "orange",
        "mostly down" = "purple"
      ),
      name = NULL
    ) +
    ggplot2::scale_y_discrete(
      drop = FALSE
    ) +
    ggplot2::scale_size_continuous(
      limits = c(1, 4),
      range = c(2, 9),
      breaks = c(
        1.5,
        2,
        2.5,
        3
      ),
      name = "|NES|"
    ) +
    ggplot2::labs(
      title = title,
      x = NULL,
      y = NULL
    ) +
    ggplot2::theme_minimal(
      base_size = 12
    ) +
    ggplot2::theme(
      panel.grid.major =
        ggplot2::element_line(
          linewidth = 0.25
        ),
      panel.grid.minor =
        ggplot2::element_blank(),
      axis.text.x =
        ggplot2::element_text(
          angle = 35,
          hjust = 1
        ),
      plot.title =
        ggplot2::element_text(
          face = "bold"
        ),
      legend.position = "right"
    )
}


# Original working plot titles retained.
p_CCl4 <- plot_theme_summary(
  CCl4_long,
  "CCl4"
)

p_DEN <- plot_theme_summary(
  DEN_long,
  "DEN"
)

p_models <- plot_theme_summary(
  models_long,
  "models"
)

p_CCl4
p_DEN
p_models


# =============================================================================
# Part 6: tumor-cell theme summary
# =============================================================================

tumorCells_mat <- tibble::tribble(
  ~Theme, ~TumorCells,
  "Fatty Acid & Lipid Metabolism", 2.277078321,
  "Cholesterol Metabolism", 2.747371368,
  "Bile Acid Metabolism & Signaling", 0,
  "Mitochondrial Function & OXPHOS", -1.509269682,
  "Xenobiotic Metabolism & Detoxification", -2.191741587,
  "Glucose Metabolism & mTOR Signaling", 2.525041591,
  "PI3K–AKT Signaling", 0,
  "Stress Response & Cell Fate", 1.777562931,
  "Iron Metabolism & Ferroptosis", 0,
  "Autophagy & Lysosomal Degradation", 0,
  "Myeloid Inflammation & Innate Immune Signaling", 1.619966263,
  "Interferon Signaling & Antigen Presentation", 0,
  "Adaptive Immunity & Immune Checkpoints", 0,
  "ECM Remodeling & Fibrosis", 2.097113612,
  "Coagulation & Hemostasis", 2.171774513,
  "Developmental Signaling (WNT NOTCH HH)", 0,
  "RTK-MAPK Signaling", 1.906747341,
  "Cell Cycle & Proliferation", -1.77975609,
  "Gene Expression Machinery", 0
)

tumorCells_mat[
  tumorCells_mat == 0
] <- NA


tumorCells_long <- tumorCells_mat %>%
  dplyr::mutate(
    Theme = factor(
      Theme,
      levels = theme_order
    )
  ) %>%
  tidyr::pivot_longer(
    cols = TumorCells,
    names_to = "CellType",
    values_to = "NES"
  ) %>%
  dplyr::filter(
    !is.na(NES)
  ) %>%
  dplyr::mutate(
    CellType = factor(CellType),
    absNES = abs(NES),
    Direction = ifelse(
      NES > 0,
      "Up in model",
      "Down in model"
    )
  )


p_tumorCells <- ggplot2::ggplot(
  tumorCells_long,
  ggplot2::aes(
    x = CellType,
    y = Theme
  )
) +
  ggplot2::geom_point(
    ggplot2::aes(
      size = absNES,
      color = Direction
    ),
    alpha = 0.95
  ) +
  ggplot2::scale_color_manual(
    values = c(
      "Up in model" = "red",
      "Down in model" = "blue"
    ),
    name = NULL
  ) +
  ggplot2::scale_y_discrete(
    drop = FALSE
  ) +
  ggplot2::scale_size_continuous(
    limits = c(1, 4),
    range = c(2, 9),
    breaks = c(
      1.5,
      2,
      2.5,
      3
    ),
    name = "|NES|"
  ) +
  ggplot2::labs(
    title = "Tumor Cells",
    x = NULL,
    y = NULL
  ) +
  ggplot2::theme_minimal(
    base_size = 12
  ) +
  ggplot2::theme(
    panel.grid.major =
      ggplot2::element_line(
        linewidth = 0.25
      ),
    panel.grid.minor =
      ggplot2::element_blank(),
    axis.text.x =
      ggplot2::element_text(
        angle = 35,
        hjust = 1
      ),
    plot.title =
      ggplot2::element_text(
        face = "bold"
      ),
    legend.position = "right"
  )

p_tumorCells
